services:
  db:
    # build: .
    # image: pgvector/pgvector:0.8.1-pg18-trixie
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres12345678

    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432

