services:
  db:
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 512mb
    environment:
      POSTGRES_PASSWORD: postgres12345678
      POSTGRES_USER: postgres

    volumes:
      - ./data:/var/lib/postgresql
  server:
    image: ghcr.io/wszgrcy/audio-server:1.0.11
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./status:/app/.status
  whisper:
    image: ghcr.io/ggml-org/whisper.cpp:main
    container_name: whisper
    # ports:
    #   - "8080:8080"
    volumes:
      - ./models:/models
    command: "\"whisper-server -et 2.0 --suppress-nst --host 0.0.0.0 -m
      /models/ggml-large-v3-turbo-q8_0.bin --request-path
      /v1/audio/transcriptions --inference-path \\\"\\\"\""
    ulimits:
      memlock:
        soft: -1
        hard: -1
